# Generated by Django 4.2.3 on 2023-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, max_length=500)),
                ('corpo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias')),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('nome_link', models.CharField(blank=True, max_length=200)),
                ('link1', models.CharField(blank=True, max_length=200)),
                ('nome_link1', models.CharField(blank=True, max_length=200)),
                ('link2', models.CharField(blank=True, max_length=200)),
                ('nome_link2', models.CharField(blank=True, max_length=200)),
                ('link3', models.CharField(blank=True, max_length=200)),
                ('nome_link3', models.CharField(blank=True, max_length=200)),
                ('link4', models.CharField(blank=True, max_length=200)),
                ('nome_link4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
