# Generated by Django 4.2.3 on 2023-07-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_noticias_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Noticias',
        ),
    ]
