# Generated by Django 4.2.3 on 2023-07-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_news_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
