# Generated by Django 4.2.3 on 2023-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='legenda',
            field=models.CharField(choices=[('esporte', 'Esporte'), ('entretenimento', 'Entretenimento'), ('política', 'Política')], default='esporte', max_length=50),
        ),
    ]
