# Generated by Django 4.2.3 on 2023-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_noticia_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='sub_legenda',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
